In [18]:
import torch

In [19]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [20]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [21]:
weights.resize_(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [22]:
activation(torch.matmul(features, weights.resize(5,1)) + bias)

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:490: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[0.1595]])

In [23]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [24]:
h1 = activation(torch.matmul(features, W1[:,0].resize(3,1)) + B1[:,0])
h2 = activation(torch.matmul(features, W1[:,1].resize(3,1)) + B1[:,1])

h = torch.cat((h1, h2),1)

out = activation(torch.matmul(h, W2) + B2)
out

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:490: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[0.3171]])

In [25]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.86991461, 0.60172268, 0.12501012],
       [0.19358499, 0.47201425, 0.67256469],
       [0.70349632, 0.44052078, 0.58311484],
       [0.56006972, 0.47407517, 0.26094551]])

In [26]:
b = torch.from_numpy(a)
b

tensor([[0.8699, 0.6017, 0.1250],
        [0.1936, 0.4720, 0.6726],
        [0.7035, 0.4405, 0.5831],
        [0.5601, 0.4741, 0.2609]], dtype=torch.float64)

In [27]:
b.numpy()

array([[0.86991461, 0.60172268, 0.12501012],
       [0.19358499, 0.47201425, 0.67256469],
       [0.70349632, 0.44052078, 0.58311484],
       [0.56006972, 0.47407517, 0.26094551]])

In [28]:

# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.7398, 1.2034, 0.2500],
        [0.3872, 0.9440, 1.3451],
        [1.4070, 0.8810, 1.1662],
        [1.1201, 0.9482, 0.5219]], dtype=torch.float64)

In [29]:
# Numpy array matches new values from Tensor
a

array([[1.73982922, 1.20344536, 0.25002024],
       [0.38716998, 0.9440285 , 1.34512939],
       [1.40699264, 0.88104157, 1.16622968],
       [1.12013944, 0.94815034, 0.52189102]])